#1,可在这里赋值为实体对象进行注入赋值
#2,然后在用到User的地方加上@Autowired即可，见Controller层
user:
  name: Tom
  age: 16
  gender: true
  stringList:
    - 河北
    - 邯郸
  birthday: 2020/09/10
  map: {key01: tom,key02: jerry}
  cat:
    name: Kitty
    gender: girl